import React from "react";
import {
  FcGlobe,
  FcEngineering,
  FcHighPriority,
  FcLeave,
  FcRating,
  FcRatings,
  FcTemplate,
  FcVideoProjector,
} from "react-icons/fc";

export const data = [
  { id: 0, cardId: 1, isMatched: false, isFlipped: false, img: <FcGlobe /> },
  { id: 0, cardId: 2, isMatched: false, isFlipped: false, img: <FcGlobe /> },
  {
    id: 1,
    cardId: 3,
    isMatched: false,
    isFlipped: false,
    img: <FcEngineering />,
  },
  {
    id: 1,
    cardId: 4,
    isMatched: false,
    isFlipped: false,
    img: <FcEngineering />,
  },
  {
    id: 2,
    cardId: 5,
    isMatched: false,
    isFlipped: false,
    img: <FcHighPriority />,
  },
  {
    id: 2,
    cardId: 6,
    isMatched: false,
    isFlipped: false,
    img: <FcHighPriority />,
  },
  { id: 3, cardId: 7, isMatched: false, isFlipped: false, img: <FcLeave /> },
  { id: 3, cardId: 8, isMatched: false, isFlipped: false, img: <FcLeave /> },
  { id: 4, cardId: 9, isMatched: false, isFlipped: false, img: <FcRating /> },
  { id: 4, cardId: 10, isMatched: false, isFlipped: false, img: <FcRating /> },
  { id: 5, cardId: 11, isMatched: false, isFlipped: false, img: <FcRatings /> },
  { id: 5, cardId: 12, isMatched: false, isFlipped: false, img: <FcRatings /> },
  {
    id: 6,
    cardId: 13,
    isMatched: false,
    isFlipped: false,
    img: <FcTemplate />,
  },
  {
    id: 6,
    cardId: 14,
    isMatched: false,
    isFlipped: false,
    img: <FcTemplate />,
  },
  {
    id: 7,
    cardId: 15,
    isMatched: false,
    isFlipped: false,
    img: <FcVideoProjector />,
  },
  {
    id: 7,
    cardId: 16,
    isMatched: false,
    isFlipped: false,
    img: <FcVideoProjector />,
  },
];
